Profile
koh1project/amiGoesFrontend pull request #38
Opened 2022-11-16 02:44 UTC by Aleirbag04

2022-11-16 03:12 UTC, jatinparmar96 requested changes

2022-11-16 03:12 UTC, jatinparmar96 commented on src/components/screens/LoginScreen.tsx
> +            Create an Account
Translations Please 😅

2022-11-16 03:12 UTC, jatinparmar96 commented on src/components/screens/createProfile/IDVerificationScreen.tsx
> +          We need to determine if the identity document is authentic and belongs
Here too

2022-11-16 03:12 UTC, jatinparmar96 commented on src/components/screens/createProfile/StepOneForm.tsx
>            Primary information is important to keep our community safe, and this
Same here

2022-11-16 04:46 UTC, ernestoguevara92 approved these changes

2022-11-16 22:13 UTC, Aleirbag04 commented on src/components/screens/createProfile/IDVerificationScreen.tsx
> +          We need to determine if the identity document is authentic and belongs
done

2022-11-16 22:13 UTC, Aleirbag04 commented on src/components/screens/createProfile/StepOneForm.tsx
>            Primary information is important to keep our community safe, and this
done

2022-11-16 22:23 UTC, Aleirbag04 commented on src/components/screens/LoginScreen.tsx
> +            Create an Account
done

2022-11-17 20:00 UTC, jatinparmar96 approved these changes

2022-11-17 20:00 UTC, merged